[package]
name = "zenocode-bin"
version = "0.1.0"
edition = "2024"

[dependencies]
zenocode-cli = { path = "../crates/interface/cli" }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
