[package]
name = "zenocode-providers-core"
version = "0.1.0"
edition = "2024"

[dependencies]
zenocode-core = { path = "../../core" }
anyhow = "1.0"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["sync"] }