[package]
name = "zenocode-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.42"
zenocode-core = { path = "../../core" }
zenocode-tui = { path = "../tui" }
# Other existing dependencies...
