[package]
name = "zenocode-completion"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["sync"] }
lazy_static = "1.4"
zenocode-core = { path = "../core" }
