[package]
name = "zenocode-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
zenocode-core = { path = "../../core" }
crossterm = "0.27"
ratatui = "0.29.0"
color-eyre = "0.6.5"
anyhow.workspace = true
# Other existing dependencies...
